"""LaTeX / venue scaffolder (VS013, `fundactional.md` §19-20).

Never fabricates venue formatting requirements: only a registered
`venues/<name>.yaml`, or the built-in `generic` fallback (which
explicitly declares it has none), can be used.
"""
from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

import yaml

from research_helper.lab import LabPaths

SECTION_NAMES: tuple[str, ...] = (
    "introduction",
    "background",
    "methodology",
    "results",
    "discussion",
    "conclusion",
)

BUILTIN_GENERIC_VENUE: dict = {
    "name": "generic",
    "template_source": "research-helper (built-in)",
    "template_version": "0.1.0",
    "requirements": {},
    "assumptions": [
        (
            "No externally verified formatting requirements are known for the "
            "generic venue. Register venues/<venue>.yaml with real, verified "
            "requirements before relying on this for an actual submission."
        )
    ],
}


def load_venue(paths: LabPaths, venue_name: str) -> dict:
    """FR-002: registered file first; `generic` has a built-in fallback;
    any other unregistered name fails clearly."""
    venue_path = paths.venues_dir / f"{venue_name}.yaml"
    if venue_path.is_file():
        return yaml.safe_load(venue_path.read_text(encoding="utf-8"))
    if venue_name == "generic":
        return dict(BUILTIN_GENERIC_VENUE)
    raise FileNotFoundError(
        f"Venue '{venue_name}' is not registered (expected {venue_path}). "
        "Register it with real, verified requirements before use — "
        "research-helper never fabricates venue formatting requirements."
    )


_MAIN_TEX_TEMPLATE = """\
% Generated by research-helper (paper init --venue {venue} --name {name})
% Venue template source: {template_source}
\\documentclass{{article}}
\\usepackage{{cite}}
\\title{{ {title} }}
\\begin{{document}}
\\maketitle
\\input{{sections/introduction}}
\\input{{sections/background}}
\\input{{sections/methodology}}
\\input{{sections/results}}
\\input{{sections/discussion}}
\\input{{sections/conclusion}}
\\bibliography{{references}}
\\end{{document}}
"""

_MAKEFILE_TEMPLATE = """\
.PHONY: build clean

build:
\tlatexmk -pdf main.tex

clean:
\tlatexmk -C
"""


def init_paper_project(paths: LabPaths, *, venue: str, name: str) -> Path:
    """FR-001, FR-004, FR-005: scaffold the §19 structure, pin the venue."""
    venue_data = load_venue(paths, venue)
    project_dir = paths.paper_projects_dir / name

    if (project_dir / "main.tex").exists():
        return project_dir

    sections_dir = project_dir / "sections"
    sections_dir.mkdir(parents=True, exist_ok=True)
    for subdir in ("figures", "tables", "assets"):
        (project_dir / subdir).mkdir(parents=True, exist_ok=True)

    for section in SECTION_NAMES:
        (sections_dir / f"{section}.tex").write_text(f"% {section.title()}\n", encoding="utf-8")

    (project_dir / "references.bib").touch()
    (project_dir / "Makefile").write_text(_MAKEFILE_TEMPLATE, encoding="utf-8")
    (project_dir / "README.md").write_text(
        f"# {name}\n\nScaffolded with venue `{venue}`. See `venue.json` for the "
        "pinned venue registry entry used at creation time.\n",
        encoding="utf-8",
    )
    (project_dir / "main.tex").write_text(
        _MAIN_TEX_TEMPLATE.format(
            venue=venue,
            name=name,
            template_source=venue_data.get("template_source", "unknown"),
            title=name,
        ),
        encoding="utf-8",
    )
    (project_dir / "venue.json").write_text(
        json.dumps(
            {**venue_data, "pinned_at": datetime.now(UTC).isoformat()}, indent=2, ensure_ascii=False
        ),
        encoding="utf-8",
    )

    return project_dir
